//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aster.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aster.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 @ShellColor 的本地化字符串。
        /// </summary>
        internal static string ShellColor {
            get {
                return ResourceManager.GetString("ShellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @ShellLanguage 的本地化字符串。
        /// </summary>
        internal static string ShellLanguage {
            get {
                return ResourceManager.GetString("ShellLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @ShellSettings 的本地化字符串。
        /// </summary>
        internal static string ShellSettings {
            get {
                return ResourceManager.GetString("ShellSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @ShellStatusBarMessage 的本地化字符串。
        /// </summary>
        internal static string ShellStatusBarMessage {
            get {
                return ResourceManager.GetString("ShellStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @ShellTheme 的本地化字符串。
        /// </summary>
        internal static string ShellTheme {
            get {
                return ResourceManager.GetString("ShellTheme", resourceCulture);
            }
        }
    }
}
